 class member2__Container extends __Widget {
    /**
     * If this method exists and has some code, a call to it will be added 
     * by Widget.php to initialize this JS class. It is called from the 
     * HTML page's "document ready" code generated by getOnReadyCode() 
     * in Widget.php. It is called only once per HTML page.
     */
    static initClass() {
        // Note: It's okay to call *super* on static methods if needed.
        // eg, super.initClass();
        // console.log('The class is ready');
    }

    /**
     * If this method exists and has some code, a call to it will be added
     * by the render() method of this widget's PHP class. It is the 
     * default render function used when generating markup 
     * using JavaScript. It should generate the markup of the widget
     * based on the given user parameters stored in "this.options". 
     * The widget's DOM container can be accessed via "this.holder".
     */
    render() {
        // For example:
        // console.log('The object "' + this.holder.id + '" is ready');
        // this.holder.style.backgroundColor = this.options.color;
        // this.holder.innerHTML = 'Hello World!';
    }

    /**
     * Respond to messages sent by this.postMessage(). It's used for intra widget
     * communication. Normally, the receiver's holder ID would be a parameter 
     * in "this.options". E.g., this.postMessage(this.options.targetWidgetId).
     * 
     * @param object data The message data sent by this.postMessage(data).
     * @return object Any return value for the caller of this.postMessage().
     */
    onMessage(data) {
        // return {};
    }
}